### ISSUE TITLE
Get math function working on point

### ISSUE THREAD

**Issue by NubeDev** [NubeDev/bac-rest#129]
We need to be able to manipulate the point value before its sent over MQTT or the API

- offset the value. 
- do some basic math, +, -, /, *

We dont need to update existing stored data

See existing modbus point node in wires as an example

![image](https://user-images.githubusercontent.com/18637436/100697949-6503a180-33eb-11eb-9911-625653f2cd43.png)

![image](https://user-images.githubusercontent.com/18637436/100697968-70ef6380-33eb-11eb-9d64-9b0f80bb7b17.png)

![image](https://user-images.githubusercontent.com/18637436/100698004-882e5100-33eb-11eb-93b0-c2c6b7f78d15.png)

**Comment by Shiny380** [comment]
- apply `offset` (like calibration) **FIRST**
- apply `math` **SECOND**
- apply `round` **LAST**
- store modified value **AFTER** operations
- don't alter any existing history stores
- update value and publish COV event if updating (`PATCH`)
